import React, { useRef, useState, useEffect, useCallback } from 'react';
import Webcam from 'react-webcam';
import { Button } from '@/components/ui/button';
import { Card } from '@/components/ui/card';
import { Input } from '@/components/ui/input';
import { Textarea } from '@/components/ui/textarea';
import { useAuth } from '@/hooks/useAuth';
import { useToast } from '@/hooks/use-toast';
import { supabase } from '@/integrations/supabase/client';
import { useLocation, useNavigate } from "react-router-dom";
import CameraModal from '@/components/CameraModal';

// Remove FILTERS, FILTER_CSS, filterIdx, and all filter carousel/filter overlay UI.
// In the video preview, remove any style applying a filter.
// Only show the video preview, recapture, and upload form.

const FILTER_THUMB_PLACEHOLDER = '/public/placeholder.svg';

const CreateVideoPage: React.FC = () => {
  const webcamRef = useRef<Webcam>(null);
  const [videoFile, setVideoFile] = useState<File | null>(null);
  const [videoUrl, setVideoUrl] = useState<string | null>(null);
  const [title, setTitle] = useState("");
  const [description, setDescription] = useState("");
  const [uploading, setUploading] = useState(false);
  const [category, setCategory] = useState('All');
  const [coverImageFile, setCoverImageFile] = useState<File | null>(null);
  const [coverImagePreview, setCoverImagePreview] = useState<string | null>(null);
  const [showCameraModal, setShowCameraModal] = useState(false);
  const { user } = useAuth();
  const { toast } = useToast();
  const location = useLocation();
  const navigate = useNavigate();

  // Read video file and preview from navigation state
  useEffect(() => {
    if (location.state && location.state.file && location.state.preview) {
      setVideoFile(location.state.file);
      setVideoUrl(location.state.preview);
    } else {
      // If no video, redirect to upload page or show message
      navigate("/upload");
    }
  }, [location.state, navigate]);

  const handleRecapture = () => {
    setShowCameraModal(true);
  };

  // Handler for when a new video is captured in CameraModal
  const handleCameraVideo = (file: File, preview: string) => {
    setVideoFile(file);
    setVideoUrl(preview);
    setCoverImageFile(null);
    setCoverImagePreview(null);
    setShowCameraModal(false);
  };

  const handleUpload = async () => {
    if (!videoFile || !user || !title.trim()) {
      toast({
        title: "Missing Information",
        description: "Please record a video and add a title",
        variant: "destructive"
      });
      return;
    }
    setUploading(true);
    try {
      let thumbnailUrl = '';
      // If user picked a custom cover image, upload it
      if (coverImageFile) {
        const coverFileName = `${user.id}/thumbnails/cover_${Date.now()}.jpg`;
        const { error: coverError } = await supabase.storage
          .from('limeytt-uploads')
          .upload(coverFileName, coverImageFile);
        if (!coverError) {
          thumbnailUrl = coverFileName;
        } else {
          toast({ title: "Cover upload failed", description: coverError.message, variant: "destructive" });
        }
      }
      // If no custom cover, thumbnailUrl remains blank (or generated by backend if needed)
      const fileExt = videoFile.name.split('.').pop();
      const fileName = `${user.id}/${Date.now()}.${fileExt}`;
      const { data, error } = await supabase.storage
        .from('limeytt-uploads')
        .upload(fileName, videoFile);
      if (error) {
        toast({
          title: "File Too Large",
          description: "Your video is too large. The maximum allowed size is 50 MB.",
          variant: "destructive"
        });
        setUploading(false);
        return;
      }
      const { data: { publicUrl } } = supabase.storage
        .from('limeytt-uploads')
        .getPublicUrl(fileName);
      const { data: profile, error: profileError } = await supabase
        .from('profiles')
        .select('username, avatar_url')
        .eq('user_id', user.id)
        .single();
      if (profileError || !profile) {
        throw new Error('Could not fetch user profile for video upload.');
      }
      const { data: insertData, error: dbError } = await supabase.from('videos').insert({
        title,
        description,
        video_url: publicUrl,
        thumbnail_url: thumbnailUrl,
        user_id: user.id,
        category,
        username: profile.username,
        avatar_url: profile.avatar_url,
      }).select();
      if (dbError) {
        throw dbError;
      }
      toast({
        title: "Upload Successful! 🎉",
        description: "Your content has been uploaded to Limey",
        className: "bg-green-600 text-white border-green-700"
      });
      setVideoFile(null);
      setVideoUrl(null);
      setTitle("");
      setDescription("");
      setCategory('All');
      setCoverImageFile(null);
      setCoverImagePreview(null);
      navigate("/upload");
    } catch (error: any) {
      toast({
        title: "Upload Failed",
        description: error.message || "Something went wrong",
        variant: "destructive"
      });
    } finally {
      setUploading(false);
    }
  };

  return (
    <div className="min-h-screen bg-background pb-20 pt-8">
      {/* Camera/filter UI section */}
      <div className="max-w-2xl mx-auto p-4">
        {/* Remove file input for initial video selection, as video comes from navigation state */}
        {!videoUrl ? (
          <div className="flex flex-col items-center justify-center h-64 border-2 border-dashed border-gray-400 rounded-lg">
            <Button variant="neon" onClick={handleRecapture}>
              Go Back
            </Button>
            <p className="text-muted-foreground mt-2">No video found. Please record a video first.</p>
          </div>
        ) : (
          <>
            <video
              src={videoUrl}
              controls
              autoPlay
              loop
              className="w-full h-64 object-cover rounded-lg mb-4"
            />
            {/* Filter carousel */}
            {/* Remove FILTERS, FILTER_CSS, filterIdx, and all filter carousel/filter overlay UI. */}
            {/* In the video preview, remove any style applying a filter. */}
            {/* Only show the video preview, recapture, and upload form. */}
            {/* Centered Recapture button below video preview */}
            <div className="flex justify-center mt-4">
              <Button variant="outline" onClick={handleRecapture}>
                Recapture
              </Button>
            </div>
            <CameraModal open={showCameraModal} onClose={() => setShowCameraModal(false)} onVideoCaptured={handleCameraVideo} />
          </>
        )}
      </div>
      {/* Upload form card below filter section */}
      {videoUrl && (
        <Card className="mt-6 p-6 max-w-md mx-auto">
          <div className="space-y-4">
            {/* Cover Image Selection */}
            <div>
              <label className="text-sm font-medium text-foreground mb-2 block">
                Cover Image
              </label>
              <div className="flex items-center gap-4 mb-2">
                <div className="w-24 h-36 bg-black rounded overflow-hidden flex items-center justify-center border border-border">
                  {coverImagePreview ? (
                    <img src={coverImagePreview} alt="Cover Preview" className="w-full h-full object-cover" />
                  ) : videoUrl ? (
                    <video src={videoUrl} className="w-full h-full object-cover" />
                  ) : (
                    <span className="text-white text-xs">No Cover</span>
                  )}
                </div>
                <div className="flex flex-col gap-2">
                  <input
                    type="file"
                    accept="image/*"
                    className="hidden"
                    id="cover-image-input"
                    onChange={e => {
                      const file = e.target.files?.[0];
                      if (file) {
                        setCoverImageFile(file);
                        setCoverImagePreview(URL.createObjectURL(file));
                      }
                    }}
                  />
                  <label htmlFor="cover-image-input">
                    <Button variant="outline" asChild className="cursor-pointer">
                      <span>Choose Cover Image</span>
                    </Button>
                  </label>
                  {coverImageFile && (
                    <Button
                      variant="ghost"
                      size="sm"
                      onClick={() => {
                        setCoverImageFile(null);
                        setCoverImagePreview(null);
                      }}
                    >
                      Use Default Thumbnail
                    </Button>
                  )}
                </div>
              </div>
              <p className="text-xs text-muted-foreground mt-1">
                Choose a custom cover image or use the default video thumbnail.
              </p>
            </div>
            <div>
              <label className="text-sm font-medium text-foreground mb-2 block">
                Title *
              </label>
              <Input
                placeholder="Give your content a catchy title..."
                value={title}
                onChange={(e) => setTitle(e.target.value)}
                maxLength={100}
              />
              <p className="text-xs text-muted-foreground mt-1">
                {title.length}/100 characters
              </p>
            </div>
            <div>
              <label className="text-sm font-medium text-foreground mb-2 block">
                Category
              </label>
              <select
                className="w-full border rounded px-3 py-2 bg-background text-foreground"
                value={category || 'All'}
                onChange={e => setCategory(e.target.value)}
                required
              >
                <option value="All">All</option>
                <option value="Bar Limes">Bar Limes</option>
                <option value="Carnival">Carnival</option>
                <option value="Comedy">Comedy</option>
                <option value="Dance">Dance</option>
                <option value="Dancehall">Dancehall</option>
                <option value="DIY Projects">DIY Projects</option>
                <option value="Educational">Educational</option>
                <option value="Events">Events</option>
                <option value="Fete">Fete</option>
                <option value="Funny Vids">Funny Vids</option>
                <option value="HOW TOs">HOW TOs</option>
                <option value="Local News">Local News</option>
                <option value="Music Vids">Music Vids</option>
                <option value="Parties">Parties</option>
                <option value="Soca">Soca</option>
                <option value="Trini Celebs">Trini Celebs</option>
              </select>
            </div>
            <div>
              <label className="text-sm font-medium text-foreground mb-2 block">
                Description
              </label>
              <Textarea
                placeholder="Tell viewers about your content..."
                value={description}
                onChange={(e) => setDescription(e.target.value)}
                maxLength={500}
                rows={4}
              />
              <p className="text-xs text-muted-foreground mt-1">
                {description.length}/500 characters
              </p>
            </div>
            <div className="flex space-x-3 pt-4">
              <Button
                variant="outline"
                onClick={handleRecapture}
                disabled={uploading}
              >
                Cancel
              </Button>
              <Button
                variant="neon"
                onClick={handleUpload}
                disabled={uploading || !title.trim()}
                className="flex-1"
              >
                {uploading ? "Uploading..." : "Share to Limey 🚀"}
              </Button>
            </div>
          </div>
        </Card>
      )}
    </div>
  );
};

export default CreateVideoPage; 