// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';
import { supabase } from "./client";

const SUPABASE_URL = "https://hhcirfvubsugcuypjyxp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImhoY2lyZnZ1YnN1Z2N1eXBqeXhwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE0MjE4OTMsImV4cCI6MjA2Njk5Nzg5M30.1B5paA-hI-zL0NG2st5xiJwecR8z9JBHzCTaAtwX38k";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});

// Function to link wallet for a specific user
export async function linkWallet(userId) {
  try {
    const { data, error } = await supabase
      .from('wallet_links')
      .insert([{ user_id: userId }]);
    
    return { data, error };
  } catch (err) {
    console.error('Exception in linkWallet:', err);
    return { data: null, error: err };
  }
}

// Function to get linked wallet for a specific user
export async function getLinkedWallet(userId) {
  try {
    const { data, error } = await supabase
      .from('wallet_links')
      .select('*')
      .eq('user_id', userId)
      .maybeSingle(); // Use maybeSingle instead of single to handle no results gracefully
    
    return { data, error };
  } catch (err) {
    console.error('Exception in getLinkedWallet:', err);
    return { data: null, error: err };
  }
}